In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7927, 2368, 3534, 5401],
 [7927, 2368, 3534, 2563],
 [7927, 989, 3534, 1078],
 [5257, 5853, 22, 4114, 4177],
 [5257, 5853, 22, 4114, 9633],
 [7406, 7927, 6802, 3534, 8355],
 [9700, 7039, 8032, 4114]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7927 2368 3534 5401]
 [   0    0    0    0 7927 2368 3534 2563]
 [   0    0    0    0 7927  989 3534 1078]
 [   0    0    0 5257 5853   22 4114 4177]
 [   0    0    0 5257 5853   22 4114 9633]
 [   0    0    0 7406 7927 6802 3534 8355]
 [   0    0    0    0 9700 7039 8032 4114]]


In [11]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 131ms/step


array([[[ 0.02110188, -0.026805  ,  0.02095454, -0.04073992,
         -0.04169066,  0.03551842,  0.04869111,  0.00488301,
          0.02583755, -0.01215434],
        [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992,
         -0.04169066,  0.03551842,  0.04869111,  0.00488301,
          0.02583755, -0.01215434],
        [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992,
         -0.04169066,  0.03551842,  0.04869111,  0.00488301,
          0.02583755, -0.01215434],
        [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992,
         -0.04169066,  0.03551842,  0.04869111,  0.00488301,
          0.02583755, -0.01215434],
        [-0.0063632 , -0.00902823, -0.02471643,  0.0225696 ,
         -0.00601302,  0.0442293 ,  0.0004213 ,  0.03218795,
          0.03539673, -0.00650965],
        [ 0.0376703 ,  0.03393921, -0.01043929, -0.04153439,
         -0.04787543,  0.04385047, -0.0480637 ,  0.00619674,
          0.03969793, -0.04707173],
        [ 0.00726063,  0.00669272, -0.03340551, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7927, 2368, 3534, 5401])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[ 0.02110188, -0.026805  ,  0.02095454, -0.04073992, -0.04169066,
         0.03551842,  0.04869111,  0.00488301,  0.02583755, -0.01215434],
       [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992, -0.04169066,
         0.03551842,  0.04869111,  0.00488301,  0.02583755, -0.01215434],
       [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992, -0.04169066,
         0.03551842,  0.04869111,  0.00488301,  0.02583755, -0.01215434],
       [ 0.02110188, -0.026805  ,  0.02095454, -0.04073992, -0.04169066,
         0.03551842,  0.04869111,  0.00488301,  0.02583755, -0.01215434],
       [-0.0063632 , -0.00902823, -0.02471643,  0.0225696 , -0.00601302,
         0.0442293 ,  0.0004213 ,  0.03218795,  0.03539673, -0.00650965],
       [ 0.0376703 ,  0.03393921, -0.01043929, -0.04153439, -0.04787543,
         0.04385047, -0.0480637 ,  0.00619674,  0.03969793, -0.04707173],
       [ 0.00726063,  0.00669272, -0.03340551, -0.00205974,  0.03105089,
        -0.00260638, -0.0013646 ,  0.0084116 